name: Snowflake dbt CI/CD Pipeline

on:
#  push:
#    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dbt-test:
    runs-on: ubuntu-latest
    environment: snowflake_dbt

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        dbt deps

    - name: Run dbt compile
      run: |
        dbt compile --profiles-dir ./profiles --target ci
      env:
        SNOWFLAKE_CI_ACCOUNT: ${{ secrets.SNOWFLAKE_CI_ACCOUNT }}
        SNOWFLAKE_CI_USER: ${{ secrets.SNOWFLAKE_CI_USER }}
        SNOWFLAKE_CI_PASSWORD: ${{ secrets.SNOWFLAKE_CI_PASSWORD }}
        SNOWFLAKE_CI_WAREHOUSE: ${{ secrets.SNOWFLAKE_CI_WAREHOUSE }}
        SNOWFLAKE_CI_PREP_DATABASE: ${{ secrets.SNOWFLAKE_CI_PREP_DATABASE }}
        SNOWFLAKE_CI_SCHEMA: ${{ secrets.SNOWFLAKE_CI_SCHEMA }}
        SNOWFLAKE_CI_ROLE: ${{ secrets.SNOWFLAKE_CI_ROLE }}

    - name: Run dbt seed and tests
      run: |
        dbt seed --profiles-dir ./profiles --target ci
        dbt test --profiles-dir ./profiles --target ci
      env:
        SNOWFLAKE_CI_ACCOUNT: ${{ secrets.SNOWFLAKE_CI_ACCOUNT }}
        SNOWFLAKE_CI_USER: ${{ secrets.SNOWFLAKE_CI_USER }}
        SNOWFLAKE_CI_PASSWORD: ${{ secrets.SNOWFLAKE_CI_PASSWORD }}
        SNOWFLAKE_CI_WAREHOUSE: ${{ secrets.SNOWFLAKE_CI_WAREHOUSE }}
        SNOWFLAKE_CI_PREP_DATABASE: ${{ secrets.SNOWFLAKE_CI_PREP_DATABASE }}
        SNOWFLAKE_CI_SCHEMA: ${{ secrets.SNOWFLAKE_CI_SCHEMA }}
        SNOWFLAKE_CI_ROLE: ${{ secrets.SNOWFLAKE_CI_ROLE }}

  dbt-deploy:
    needs: dbt-test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: snowflake_dbt

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        dbt deps

    - name: Deploy dbt models
      run: |
        dbt run --profiles-dir ./profiles --target ci
      env:
        SNOWFLAKE_CI_ACCOUNT: ${{ secrets.SNOWFLAKE_CI_ACCOUNT }}
        SNOWFLAKE_CI_USER: ${{ secrets.SNOWFLAKE_CI_USER }}
        SNOWFLAKE_CI_PASSWORD: ${{ secrets.SNOWFLAKE_CI_PASSWORD }}
        SNOWFLAKE_CI_WAREHOUSE: ${{ secrets.SNOWFLAKE_CI_WAREHOUSE }}
        SNOWFLAKE_CI_PREP_DATABASE: ${{ secrets.SNOWFLAKE_CI_PREP_DATABASE }}
        SNOWFLAKE_CI_SCHEMA: ${{ secrets.SNOWFLAKE_CI_SCHEMA }}
        SNOWFLAKE_CI_ROLE: ${{ secrets.SNOWFLAKE_CI_ROLE }}